{
  "openapi": "3.1.0",
  "info": {
    "title": "Playbook API Documentation",
    "description": "This is the documentation for the Playbook API. You can use this API to use our service programmatically, this is done by using your API key. <br/> You can view your API key using the 'User' tab on https://beta.playbook3d.com/.",
    "version": "1.0"
  },
  "paths": {
    "/template": {
      "post": {
        "tags": ["text-to-speech"],
        "summary": "Text To Speech",
        "description": "Converts text into speech using a voice of your choice and returns audio.",
        "operationId": "Text_to_speech_v1_text_to_speech__voice_id__post",
        "parameters": [
          {
            "description": "Voice ID to be used, you can use https://api.elevenlabs.io/v1/voices to list all the available voices.",
            "required": true,
            "schema": {
              "type": "string",
              "title": "Voice Id",
              "description": "Voice ID to be used, you can use https://api.elevenlabs.io/v1/voices to list all the available voices."
            },
            "example": "21m00Tcm4TlvDq8ikWAM",
            "name": "voice_id",
            "in": "path"
          },
          {
            "description": "When enable_logging is set to false full privacy mode will be used for the request. This will mean history features are unavailable for this request, including request stitching. Full privacy mode may only be used by enterprise customers.",
            "required": false,
            "schema": {
              "type": "boolean",
              "title": "Enable request logging.",
              "description": "When enable_logging is set to false full privacy mode will be used for the request. This will mean history features are unavailable for this request, including request stitching. Full privacy mode may only be used by enterprise customers.",
              "default": true
            },
            "name": "enable_logging",
            "in": "query"
          },
          {
            "description": "You can turn on latency optimizations at some cost of quality. The best possible final latency varies by model. Possible values:\n0 - default mode (no latency optimizations)\n1 - normal latency optimizations (about 50% of possible latency improvement of option 3)\n2 - strong latency optimizations (about 75% of possible latency improvement of option 3)\n3 - max latency optimizations\n4 - max latency optimizations, but also with text normalizer turned off for even more latency savings (best latency, but can mispronounce eg numbers and dates).\n\nDefaults to None.\n",
            "required": false,
            "deprecated": true,
            "schema": {
              "type": "integer",
              "title": "DEPRECATED. How much we should optimize streaming request latency (time to first audio byte).",
              "description": "You can turn on latency optimizations at some cost of quality. The best possible final latency varies by model. Possible values:\n0 - default mode (no latency optimizations)\n1 - normal latency optimizations (about 50% of possible latency improvement of option 3)\n2 - strong latency optimizations (about 75% of possible latency improvement of option 3)\n3 - max latency optimizations\n4 - max latency optimizations, but also with text normalizer turned off for even more latency savings (best latency, but can mispronounce eg numbers and dates).\n\nDefaults to None.\n"
            },
            "name": "optimize_streaming_latency",
            "in": "query"
          },
          {
            "description": "Output format of the generated audio. Must be one of:\nmp3_22050_32 - output format, mp3 with 22.05kHz sample rate at 32kbps.\nmp3_44100_32 - output format, mp3 with 44.1kHz sample rate at 32kbps.\nmp3_44100_64 - output format, mp3 with 44.1kHz sample rate at 64kbps.\nmp3_44100_96 - output format, mp3 with 44.1kHz sample rate at 96kbps.\nmp3_44100_128 - default output format, mp3 with 44.1kHz sample rate at 128kbps.\nmp3_44100_192 - output format, mp3 with 44.1kHz sample rate at 192kbps. Requires you to be subscribed to Creator tier or above.\npcm_16000 - PCM format (S16LE) with 16kHz sample rate.\npcm_22050 - PCM format (S16LE) with 22.05kHz sample rate.\npcm_24000 - PCM format (S16LE) with 24kHz sample rate.\npcm_44100 - PCM format (S16LE) with 44.1kHz sample rate. Requires you to be subscribed to Pro tier or above.\nulaw_8000 - μ-law format (sometimes written mu-law, often approximated as u-law) with 8kHz sample rate. Note that this format is commonly used for Twilio audio inputs.\n",
            "required": false,
            "schema": {
              "type": "string",
              "title": "Output format of the generated audio.",
              "description": "Output format of the generated audio. Must be one of:\nmp3_22050_32 - output format, mp3 with 22.05kHz sample rate at 32kbps.\nmp3_44100_32 - output format, mp3 with 44.1kHz sample rate at 32kbps.\nmp3_44100_64 - output format, mp3 with 44.1kHz sample rate at 64kbps.\nmp3_44100_96 - output format, mp3 with 44.1kHz sample rate at 96kbps.\nmp3_44100_128 - default output format, mp3 with 44.1kHz sample rate at 128kbps.\nmp3_44100_192 - output format, mp3 with 44.1kHz sample rate at 192kbps. Requires you to be subscribed to Creator tier or above.\npcm_16000 - PCM format (S16LE) with 16kHz sample rate.\npcm_22050 - PCM format (S16LE) with 22.05kHz sample rate.\npcm_24000 - PCM format (S16LE) with 24kHz sample rate.\npcm_44100 - PCM format (S16LE) with 44.1kHz sample rate. Requires you to be subscribed to Pro tier or above.\nulaw_8000 - μ-law format (sometimes written mu-law, often approximated as u-law) with 8kHz sample rate. Note that this format is commonly used for Twilio audio inputs.\n",
              "default": "mp3_44100_128"
            },
            "name": "output_format",
            "in": "query"
          },
          {
            "description": "Your API key. This is required by most endpoints to access our API programatically. You can view your xi-api-key using the 'Profile' tab on the website.",
            "required": false,
            "schema": {
              "type": "string",
              "title": "Xi-Api-Key",
              "description": "Your API key. This is required by most endpoints to access our API programatically. You can view your xi-api-key using the 'Profile' tab on the website."
            },
            "name": "xi-api-key",
            "in": "header"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Body_Text_to_speech_v1_text_to_speech__voice_id__post"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "audio/mpeg": {}
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        },
        "x-codeSamples": [
          {
            "lang": "Python",
            "source": "from elevenlabs import ElevenLabs\n\nclient = ElevenLabs(\n    api_key=\"YOUR_API_KEY\",\n)\nclient.text_to_speech.convert(\n    voice_id=\"21m00Tcm4TlvDq8ikWAM\",\n    model_id=\"eleven_multilingual_v2\",\n    text=\"Hello! 你好! Hola! नमस्ते! Bonjour! こんにちは! مرحبا! 안녕하세요! Ciao! Cześć! Привіт! வணக்கம்!\",\n)\n"
          },
          {
            "lang": "JavaScript",
            "source": "import { ElevenLabsClient } from \"elevenlabs\";\n\nconst client = new ElevenLabsClient({ apiKey: \"YOUR_API_KEY\" });\nawait client.textToSpeech.convert(\"21m00Tcm4TlvDq8ikWAM\", {\n    model_id: \"eleven_multilingual_v2\",\n    text: \"Hello! 你好! Hola! नमस्ते! Bonjour! こんにちは! مرحبا! 안녕하세요! Ciao! Cześć! Привіт! வணக்கம்!\"\n});\n"
          },
          {
            "lang": "cURL",
            "source": "curl --request POST \\\n  --url https://api.elevenlabs.io/v1/text-to-speech/21m00Tcm4TlvDq8ikWAM \\\n  --header 'xi-api-key: YOUR_API_KEY' \\\n  --header 'Content-Type: application/json' \\\n  --data '{\n    \"text\": \"Hello! 你好! Hola! नमस्ते! Bonjour! こんにちは! مرحبا! 안녕하세요! Ciao! Cześć! Привіт! வணக்கம்!\",\n    \"model_id\": \"eleven_multilingual_v2\"\n  }'"
          }
        ]
      }
    },
    "/upload-image":{
      "post":{
        "tags": ["upload-image"],
        "summary": "Upload image",
        "description": "Uploads image to Playbook3d's servers.",
        "operationId": "upload_image",
        "parameters": [
          {
            "description": "Your API key. This is required by most endpoints to access our API programatically. You can view your x-api-key using the 'Profile' tab on the website.",
            "required": false,
            "schema": {
              "type": "string",
              "title": "X-Api-Key",
              "description": "Your API key. This is required by most endpoints to access our API programatically. You can view your x-api-key using the 'Profile' tab on the website."
            },
            "name": "x-api-key",
            "in": "header"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/upload_image_post"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties":{
                    "message":{
                      "type": "string"
                    }
                  },
                  "example":{
                    "message": "Image Uploaded succesfully"
                  }
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        },
        "x-codeSamples": [
          {
            "lang": "Python",
            "source": "from playbookNetworkClient import PlaybookClient\n\n def setup(self):\n self.playbookClient = PlaybookClient()\n self.playbookClient.set_api_key({your api key})\n\n def upload_image(self, image: Union[str, bytes]):\n  result = self.playbookClient.upload_image_to_playbook(image)"
          },
          {
            "lang": "JavaScript",
            "source": ""
          },
          {
            "lang": "C#",
            "source": "RunWorkflowProperties data =\n\tnew()\n\t{\n\t\tid = {workflow_id},\n\t\torigin = \"2\",\n\t\tinputs = new { },\n\t};"
          }
        ]
      }
    },
    "/upload-video":{
      "post":{
        "tags": ["upload-video"],
        "summary": "Upload video",
        "description": "Uploads video to Playbook3d's servers.",
        "operationId": "video",
        "parameters": [
          {
            "description": "Your API key. This is required by most endpoints to access our API programatically. You can view your x-api-key using the 'Profile' tab on the website.",
            "required": false,
            "schema": {
              "type": "string",
              "title": "X-Api-Key",
              "description": "Your API key. This is required by most endpoints to access our API programatically. You can view your x-api-key using the 'Profile' tab on the website."
            },
            "name": "x-api-key",
            "in": "header"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/upload_image_post"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties":{
                    "message":{
                      "type": "string"
                    }
                  },
                  "example":{
                    "message": "Image Uploaded succesfully"
                  }
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        },
        "x-codeSamples": [
          {
            "lang": "Python",
            "source": "from playbookNetworkClient import PlaybookClient\n\n def setup(self):\n self.playbookClient = PlaybookClient()\n self.playbookClient.set_api_key({your api key})\n\n def upload_video(self, video: Union[str, bytes]):\n  result = self.playbookClient.upload_video_to_playbook(video)"
          },
          {
            "lang": "JavaScript",
            "source": ""
          },
          {
            "lang": "C#",
            "source": "RunWorkflowProperties data =\n\tnew()\n\t{\n\t\tid = {workflow_id},\n\t\torigin = \"2\",\n\t\tinputs = new { },\n\t};"
          }
        ]
      }
    },
    "/run-workflow/{team_id}/{run_id}": {
      "post": {
        "tags": ["run-workflow"],
        "summary": "Run Workflow",
        "description": "Runs specified workflow.",
        "operationId": "run_workflow",
        "parameters": [
          {
            "description": "Your API key. This is required by most endpoints to access our API programatically. You can view your x-api-key using the 'Profile' tab on the website.",
            "required": false,
            "schema": {
              "type": "string",
              "title": "X-Api-Key",
              "description": "Your API key. This is required by most endpoints to access our API programatically. You can view your x-api-key using the 'Profile' tab on the website."
            },
            "name": "x-api-key",
            "in": "header"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/run_workflow_post"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties":{
                    "run_id":{
                      "type": "string"
                    },
                    "status":{
                      "type": "string"
                    },
                    "message":{
                      "type": "string"
                    }
                  },
                  "example":{
                    "run_id": "uuid",
                    "status": "queued",
                    "message": "Workflow submitted to ComfyUI Server"
                  }
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        },
        "x-codeSamples": [
          {
            "lang": "Python",
            "source": "from playbookNetworkClient import PlaybookClient\n\n def setup(self):\n self.playbookClient = PlaybookClient()\n self.playbookClient.set_api_key({your api key})\n\n def run_workflow(self, workflow: PlaybookWorkflow):\n  result = self.playbookClient.run_workflow({workflow})"
          },
          {
            "lang": "JavaScript",
            "source": ""
          },
          {
            "lang": "C#",
            "source": "RunWorkflowProperties data =\n\tnew()\n\t{\n\t\tid = {workflow_id},\n\t\torigin = \"2\",\n\t\tinputs = new { },\n\t};"
          }
        ]
      }
    },
    "/workflows/{workflow_id}": {
      "get": {
        "tags": ["run-workflow"],
        "summary": "Run Workflow",
        "description": "Runs specified workflow.",
        "operationId": "run_workflow",
        "parameters": [
          {
            "description": "Your API key. This is required by most endpoints to access our API programatically. You can view your x-api-key using the 'Profile' tab on the website.",
            "required": false,
            "schema": {
              "type": "string",
              "title": "X-Api-Key",
              "description": "Your API key. This is required by most endpoints to access our API programatically. You can view your x-api-key using the 'Profile' tab on the website."
            },
            "name": "x-api-key",
            "in": "header"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/run_workflow_post"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "audio/mpeg": {}
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        },
        "x-codeSamples": [
          {
            "lang": "Python",
            "source": ""
          },
          {
            "lang": "JavaScript",
            "source": ""
          },
          {
            "lang": "C#",
            "source": ""
          }
        ]
      },
      "delete": {
        "tags": ["run-workflow"],
        "summary": "Run Workflow",
        "description": "Runs specified workflow.",
        "operationId": "run_workflow",
        "parameters": [
          {
            "description": "Your API key. This is required by most endpoints to access our API programatically. You can view your x-api-key using the 'Profile' tab on the website.",
            "required": false,
            "schema": {
              "type": "string",
              "title": "X-Api-Key",
              "description": "Your API key. This is required by most endpoints to access our API programatically. You can view your x-api-key using the 'Profile' tab on the website."
            },
            "name": "x-api-key",
            "in": "header"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/run_workflow_post"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "audio/mpeg": {}
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        },
        "x-codeSamples": [
          {
            "lang": "Python",
            "source": ""
          },
          {
            "lang": "JavaScript",
            "source": ""
          },
          {
            "lang": "C#",
            "source": ""
          }
        ]
      },
      "patch": {
        "tags": ["run-workflow"],
        "summary": "Run Workflow",
        "description": "Runs specified workflow.",
        "operationId": "run_workflow",
        "parameters": [
          {
            "description": "Your API key. This is required by most endpoints to access our API programatically. You can view your x-api-key using the 'Profile' tab on the website.",
            "required": false,
            "schema": {
              "type": "string",
              "title": "X-Api-Key",
              "description": "Your API key. This is required by most endpoints to access our API programatically. You can view your x-api-key using the 'Profile' tab on the website."
            },
            "name": "x-api-key",
            "in": "header"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/run_workflow_post"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "audio/mpeg": {}
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        },
        "x-codeSamples": [
          {
            "lang": "Python",
            "source": ""
          },
          {
            "lang": "JavaScript",
            "source": ""
          },
          {
            "lang": "C#",
            "source": ""
          }
        ]
      }
    },
    "/workflows": {
      "get": {
        "tags": ["get-workflow"],
        "summary": "Gets all user's workflows",
        "description": "Get all workflows.",
        "operationId": "get_workflow",
        "parameters": [
          {
            "description": "Your API key. This is required by most endpoints to access our API programatically. You can view your x-api-key using the 'Profile' tab on the website.",
            "required": true,
            "schema": {
              "type": "string",
              "title": "X-Api-Key",
              "description": "Your API key. This is required by most endpoints to access our API programatically. You can view your x-api-key using the 'Profile' tab on the website."
            },
            "name": "x-api-key",
            "in": "header"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema":{
                  "type":"object",
                  "properties": {
                    "id":{
                      "type":"string"
                    },
                    "name":{
                      "type":"string"
                    },
                    "owner_id":{
                      "type":"string"
                    },
                    "team_id":{
                      "type":"string"
                    },
                    "is_external":{
                      "type":"boolean"
                    },
                    "canvas_type":{
                      "type":"string"
                    },
                    "public":{
                      "type":"boolean"
                    },
                    "last_form_data":{
                      "type":"object"
                    },
                    "s3_file_id":{
                      "type":"string"
                    },
                    "workflow_url":{
                      "type":"string"
                    },
                    "workflow_api_url":{
                      "type":"string"
                    },
                    "public_url":{
                      "type":"string"
                    },
                    "cover":{
                      "type":"string"
                    },
                    "modal_app_ids":{
                      "type":"object"
                    },
                    "editing_user":{
                      "type":"object"
                    },
                    "editing_user_id":{
                      "type":"string"
                    }
                  },
                  "example":{
                    "id": "uuid",
                    "name": "Workflow",
                    "owner_id": "uuid",
                    "team_id": "uuid",
                    "is_external": false,
                    "canvas_type": "2d",
                    "public": true,
                    "last_form_data": {},
                    "s3_file_id": "uuid",
                    "workflow_url": "url",
                    "workflow_api_url": "url",
                    "public_url": "url",
                    "cover": "url",
                    "modal_app_ids": {},
                    "editing_user": { "PlaybookUser": {}},
                    "editing_user_id": "uuid"
                  }
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        },
        "x-codeSamples": [
          {
            "lang": "Python",
            "source": "from playbookNetworkClient import PlaybookClient\n\n def setup(self):\n self.playbookClient = PlaybookClient() \n self.playbook_client.set_api_key({your api key}) \n\n def get_workflows(self):\n  workflows = self.playbookClient.get_user_workflows()"
          },
          {
            "lang": "JavaScript",
            "source": ""
          },
          {
            "lang": "C#",
            "source": ""
          }
        ]
      },
      "post": {
        "tags": ["run-workflow"],
        "summary": "Run Workflow",
        "description": "Runs specified workflow.",
        "operationId": "run_workflow",
        "parameters": [
          {
            "description": "Your API key. This is required by most endpoints to access our API programatically. You can view your x-api-key using the 'Profile' tab on the website.",
            "required": false,
            "schema": {
              "type": "string",
              "title": "X-Api-Key",
              "description": "Your API key. This is required by most endpoints to access our API programatically. You can view your x-api-key using the 'Profile' tab on the website."
            },
            "name": "x-api-key",
            "in": "header"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/run_workflow_post"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "audio/mpeg": {}
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        },
        "x-codeSamples": [
          {
            "lang": "Python",
            "source": ""
          },
          {
            "lang": "JavaScript",
            "source": ""
          },
          {
            "lang": "C#",
            "source": ""
          }
        ]
      }
    },
    "/teams": {
      "get": {
        "tags": ["get-teams"],
        "summary": "Gets all user's teams",
        "description": "Gets all user's teams.",
        "operationId": "get-teams",
        "parameters": [
          {
            "description": "Your API key. This is required by most endpoints to access our API programatically. You can view your x-api-key using the 'Profile' tab on the website.",
            "required": true,
            "schema": {
              "type": "string",
              "title": "X-Api-Key",
              "description": "Your API key. This is required by most endpoints to access our API programatically. You can view your x-api-key using the 'Profile' tab on the website."
            },
            "name": "x-api-key",
            "in": "header"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema":{
                  "type":"object",
                  "properties":{
                    "id":{
                      "type":"string"
                    },
                    "name":{
                      "type":"string"
                    },
                    "owner_id":{
                      "type":"string"
                    },
                    "last_login":{
                      "type":"string"
                    },
                    "gpu_usage_total":{
                      "type":"integer"
                    },
                    "gpu_usage_billing_period":{
                      "type":"integer"
                    },
                    "modal_app_ids":{
                      "type":"object"
                    },
                    "has_active_subscription":{
                      "type":"boolean"
                    },
                    "credits":{
                      "type":"integer"
                    },
                    "api_key":{
                      "type":"string"
                    },
                    "members":{
                      "type":"object"
                    },
                    "private_models":{
                      "type":"object"
                    },
                    "workflows":{
                      "type":"object"
                    }
                  },
                  "example":{
                    "id": "uuid",
                    "name": "Personal Team",
                    "owner_id": "uuid",
                    "last_login": "date",
                    "gpu_usage_total": 1000,
                    "gpu_usage_billing_period": 200,
                    "modal_app_ids": {},
                    "has_active_subscription": true,
                    "credits": 999,
                    "api_key": "uuid",
                    "members": {},
                    "private_models": { "PlaybookPrivateModels": {}},
                    "workflows": {"PlaybookWorkflows": {}}
                  }
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        },
        "x-codeSamples": [
          {
            "lang": "Python",
            "source": "from playbookNetworkClient import PlaybookClient\n\n def setup(self):\n self.playbookClient = PlaybookClient()\n self.playbookClient.set_api_key({your api key})\n\n def get_teams(self):\n  teams = self.playbookClient.get_user_teams()"
          },
          {
            "lang": "JavaScript",
            "source": ""
          },
          {
            "lang": "C#",
            "source": ""
          }
        ]
      }
    },
    "/teams/{team_id}": {
      "get": {
        "tags": ["run-workflow"],
        "summary": "Run Workflow",
        "description": "Runs specified workflow.",
        "operationId": "run_workflow",
        "parameters": [
          {
            "description": "Your API key. This is required by most endpoints to access our API programatically. You can view your x-api-key using the 'Profile' tab on the website.",
            "required": false,
            "schema": {
              "type": "string",
              "title": "X-Api-Key",
              "description": "Your API key. This is required by most endpoints to access our API programatically. You can view your x-api-key using the 'Profile' tab on the website."
            },
            "name": "x-api-key",
            "in": "header"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/run_workflow_post"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "audio/mpeg": {}
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        },
        "x-codeSamples": [
          {
            "lang": "Python",
            "source": ""
          },
          {
            "lang": "JavaScript",
            "source": ""
          },
          {
            "lang": "C#",
            "source": ""
          }
        ]
      }
    },"/users": {
      "get": {
        "tags": ["get-users"],
        "summary": "Gets the current Playbook User",
        "description": "Gets the current Playbook User",
        "operationId": "get-users",
        "parameters": [
          {
            "description": "Your API key. This is required by most endpoints to access our API programatically. You can view your x-api-key using the 'Profile' tab on the website.",
            "required": true,
            "schema": {
              "type": "string",
              "title": "X-Api-Key",
              "description": "Your API key. This is required by most endpoints to access our API programatically. You can view your x-api-key using the 'Profile' tab on the website."
            },
            "name": "x-api-key",
            "in": "header"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema":{
                  "type":"object",
                  "properties": {
                    "id":{
                      "type":"string"
                    },
                    "cognito_id":{
                      "type":"string"
                    },
                    "tier_id":{
                      "type":"string"
                    },
                    "email":{
                      "type":"string"
                    },
                    "status":{
                      "type":"string"
                    },
                    "user_type":{
                      "type":"string"
                    },
                    "name":{
                      "type":"string"
                    },
                    "gpu_usage_total":{
                      "type":"integer"
                    },
                    "gpu_usage_billing_period":{
                      "type":"integer"
                    }
                  },
                  "example":{
                    "id": "uuid",
                    "cognito_id": "uuid",
                    "tier_id": "uuid",
                    "email": "user@domain.com",
                    "status": "Active",
                    "user_type": "normal",
                    "name": "John Doe",
                    "gpu_usage_total": 250,
                    "gpu_usage_billing_period": 250
                  }
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        },
        "x-codeSamples": [
          {
            "lang": "Python",
            "source": "from playbookNetworkClient import PlaybookClient\n\n def setup(self):\n self.playbookClient = PlaybookClient()\n self.playbookClient.set_api_key({your api key})\n\n def get_user(self):\n  user = self.playbookClient.get_user_data()"
          },
          {
            "lang": "JavaScript",
            "source": ""
          },
          {
            "lang": "C#",
            "source": ""
          }
        ]
      }
    },
    "/runs": {
      "get": {
        "tags": ["runs"],
        "summary": "Gets all the playbook runs associated with your account",
        "description": "Gets playbook runs.",
        "operationId": "get-runs",
        "parameters": [
          {
            "description": "Your API key. This is required by most endpoints to access our API programatically. You can view your x-api-key using the 'Profile' tab on the website.",
            "required": true,
            "schema": {
              "type": "string",
              "title": "X-Api-Key",
              "description": "Your API key. This is required by most endpoints to access our API programatically. You can view your x-api-key using the 'Profile' tab on the website."
            },
            "name": "x-api-key",
            "in": "header"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "id":{
                      "type": "string"
                    },
                    "platform":{
                      "type": "string"
                    },
                    "status":{
                      "type": "string"
                    },
                    "progress":{
                      "type": "integer"
                    },
                    "duration":{
                      "type": "integer"
                    },
                    "webhook_url":{
                      "type": "string"
                    },
                    "run_result":{
                      "type": "string"
                    },
                    "team":{
                      "type": "object"
                    },
                    "owner":{
                      "type": "object"
                    },
                    "workflow":{
                      "type": "object"
                    }
                  },
                  "type": "object",
                  "example": {
                    "id": "uuid",
                    "platform": "web",
                    "status": "Completed",
                    "progress": 100,
                    "duration": 5,
                    "webhook_url": "url",
                    "run_result": "result url",
                    "team": {"PlaybookTeam": {}},
                    "owner": {"PlaybookUser": {}},
                    "workflow": {"PlaybookWorkflow": {}}
                  }
                  
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        },
        "x-codeSamples": [
          {
            "lang": "Python",
            "source": "from playbookNetworkClient import PlaybookClient\n\n def setup(self):\n self.playbookClient = PlaybookClient()\n self.playbookClient.set_api_key({your api key})\n\n def get_runs(self):\n  teams = self.playbookClient.get_user_runs()"
          },
          {
            "lang": "JavaScript",
            "source": ""
          },
          {
            "lang": "C#",
            "source": ""
          }
        ]
      }
    }
  },
  "components": {
    "schemas": {
      "HTTPValidationError": {
        "properties": {
          "detail": {
            "items": {
              "$ref": "#/components/schemas/ValidationError"
            },
            "type": "array",
            "title": "Detail"
          }
        },
        "type": "object",
        "title": "HTTPValidationError"
      },
      "run_workflow_post": {
        "properties": {
          "id": {
            "type": "string",
            "description": "The id of the workflow to run."
          },
          "origin": {
            "type": "string",
            "description": "2 indicates Unity SDK."
          },
          "inputs": {
            "type": "object",
            "description": "Optional array of inputs to override workflow defaults"
          }
        },
        "type": "object",
        "required": ["id", "origin"],
        "title": "run_workflow__voice_id__post"
      },
      "upload_image_post": {
        "properties": {
          "file_path": {
            "type": "string",
            "description": "The file path to upload."
          },
          "file":{
            "type": "object",
            "description": "File binary to upload"
          }
        },
        "type": "object",
        "required": [],
        "title": "upload_image"
      }
    }
  },
  "tags": []
}
